### ISSUE TITLE
Might be worth having differentiating between Item Description and Player Notes

### ISSUE THREAD

**Issue by AkiranBlade** [SocratesEU/entropiawikitesting#11]
The in-game items each have a flavour text and so this should be it's own field. 

Then players can add other notes about an item, such as when explaining how the buff works or how to use a type of item and this will be obviously separate from the flavour text.

**Comment by SocratesEU** [comment]
Item Descriptions in the next update will be:
First section as a dynamically generated description with internal links
Second section for user generated description
