### ISSUE TITLE
Looted from table has inconsistent cell padding and all grid cells with a link have the same problem.

### ISSUE THREAD

**Issue by AkiranBlade** [SocratesEU/entropiawikitesting#12]
Observed from Weapons listing, going into Weapons pages where the weapon has "looted from:" data, the padding of the "Creature" and "Item" cells is missing it seems?

Actually, it seems in addition to the "Item" cell of the looted from table, all grids that contain a link are presenting the same issue.

![image](https://github.com/user-attachments/assets/ea35e890-da19-4433-a06b-4e353a3c98e0)

**Comment by SocratesEU** [comment]
Resolved (kind of) new table system got rid of that.
