### ISSUE TITLE
No obvious "Back button" from an item page

### ISSUE THREAD

**Issue by AkiranBlade** [SocratesEU/entropiawikitesting#14]
I know the browser back button can be used, however the item pages themselves seem to be missing a "<" link to take you back to the grid, and on top of this; when you filter a grid there is no real time URI update with the filtering information. 

This means when you hit the back button, you're at the mercy of the browser remembering there was a filter action page. If you update the URI with each change to the filter, I think the navigation flow will be more robust.

**Comment by SocratesEU** [comment]
All detail pages now have a "go back to category" button. Placement can be put to poll and changed later. Live in next revision.
