### ISSUE TITLE
Discussion: I'm not sure about numeric cells being centre justified.

### ISSUE THREAD

**Issue by AkiranBlade** [SocratesEU/entropiawikitesting#16]
Raising this issue as a discussion point.

Because a lot of the time when you're viewing a wiki, you'll want to compare items; having numeric cells centre justified feels a bit off to me. Or this me being too old school?

**Comment by SocratesEU** [comment]
Semi-fixed. Agree that numerical values should be right aligned. I've implemented a fix that attempts to detect what it should be and apply it from there. It's got issues and has a small performance impact but I think it's serviceable for now, and will be refactored at a later point when I due some efficiency passovers on the code.
