### ISSUE TITLE
Clicking on any attribute from another table, weapon / mob gives you an error

### ISSUE THREAD

**Issue by lordorm** [SocratesEU/entropiawikitesting#24]
clicking on any attribute gives you an error like this:
ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

tried on https://entropiawiki-test-slt6was5kq-ew.a.run.app/detail?ctype=creatures&search=Combat%3A%20Combat%20Sense as example

**Comment by AkiranBlade** [comment]
I think this is specific to the skills gained from mob table, because it places the Category in front of the skill name, then using that name is invalid on the main type table.

**Comment by SocratesEU** [comment]
Fixed. Clicking on a skill from either a Creature or Weapon page will now correctly direct to corresponding skill page. Live in next revision.
