### ISSUE TITLE
Can not use the arrows on the left of the name in the colum to sort the results

### ISSUE THREAD

**Issue by lordorm** [SocratesEU/entropiawikitesting#26]
When trying to use the arrows in the table to sort the results the arrows dont work.
![image](https://github.com/user-attachments/assets/bb6ec26d-29e0-4d9f-92e5-d37c80b6b142)

**Comment by SocratesEU** [comment]
Pointer Event disabled issue (note for me)

**Comment by SocratesEU** [comment]
Now Resolved. Reintroduced another issue but I'll find a different way to solve that.
