### ISSUE TITLE
The hover over row CSS is causing the hovered row to grow

### ISSUE THREAD

**Issue by AkiranBlade** [SocratesEU/entropiawikitesting#8]
Because the hovered over row grows when you hover over it, all the other data below jiggles around a bit which isn't ideal.

This is on MS Edge.

**Comment by SocratesEU** [comment]
Could you be more specific as to which table/url you experienced this on? And a screenshot if possible, thanks!

**Comment by AkiranBlade** [comment]
Every single grid does this for me.

**Comment by SocratesEU** [comment]
Strange, I can't replicate this. Could you provide a screenshot or clip? Thank you

**Comment by AkiranBlade** [comment]
![CSS Grid issue](https://github.com/user-attachments/assets/54ead0fb-824b-48e7-8271-216f4d22e712)

**Comment by AkiranBlade** [comment]
Not great quality sorry.

**Comment by SocratesEU** [comment]
Fixed. Live in next revision.
