### ISSUE TITLE
Weapon Attachments Table

### ISSUE THREAD

**Issue by AkiranBlade** [SocratesEU/entropiawikitesting#9]
This is probably more of a discussion point. I don't see a huge amount of value in having amps, absorbers and sightings all lumped into one presented table.

Instead these could really be split into the appropriate categories (even if they live in the same data table.)

If someone feels there is a real utility in having them all in the same table, please comment below.

**Comment by SocratesEU** [comment]
Agree with this one, I will split them out.

**Comment by SocratesEU** [comment]
Resolved. Live in next revision.
